import { useCallback, useEffect, useRef, useState, type RefObject } from 'react';
import type { HistoryEntry, Message, WPItem } from '../types';
import { generateContent, generateContentStream } from '../api';
import { extractHtml } from '../util/aiDesignerHelpers';

type UseAiConversationOptions = {
  apiUrl: string;
  previewHtml: string | null;
  originalPreviewHtml: string | null;
  publishTitle: string;
  selectedItem: WPItem | null;
  selectedBlockIndex: string | null;
  selectedBlockHtml: string | null;
  iframeRef: RefObject<HTMLIFrameElement>;
  setPreviewHtml: (value: string | null) => void;
  setPublishTitle: (value: string) => void;
  setMetaTitle: (value: string) => void;
  setMetaExcerpt: (value: string) => void;
  setMetaFeaturedImageUrl: (value: string | null) => void;
  clearSelection: (iframeRef?: RefObject<HTMLIFrameElement>) => void;
};

type UseAiConversationResult = {
  messages: Message[];
  input: string;
  isLoading: boolean;
  historyEntries: HistoryEntry[];
  isHistoryOpen: boolean;
  hasAIGenerated: boolean;
  publishTitle: string;
  chatMessagesRef: RefObject<HTMLDivElement>;
  setInput: (value: string) => void;
  setIsHistoryOpen: (value: boolean | ((prev: boolean) => boolean)) => void;
  setPublishTitle: (value: string) => void;
  handleSend: (overrideText?: string) => Promise<void>;
  handleConfirmRevertChanges: () => void;
  handleRevertToEntry: (id: string) => void;
  resetAiConversation: () => void;
  appendAssistantMessage: (message: Message) => void;
};

const REMOVAL_KEYWORDS = [ 'remove', 'delete', 'get rid of', 'take out', 'eliminate', 'cut this', 'hide this' ];
const CONTENT_QUALIFIERS = [ 'text', 'content', 'words', 'copy', 'inside', 'within', 'from this', 'heading', 'paragraph', 'image' ];

// Strict: removal of the whole block (no content-qualifier phrases present).
const isRemovalIntent = ( text: string ): boolean => {
  const lower = text.toLowerCase();
  if ( ! REMOVAL_KEYWORDS.some( ( kw ) => lower.includes( kw ) ) ) {
    return false;
  }
  if ( CONTENT_QUALIFIERS.some( ( q ) => lower.includes( q ) ) ) {
    return false;
  }
  return true;
};

// Broad: any removal keyword regardless of content qualifiers.
const hasRemovalKeyword = ( text: string ): boolean => {
  const lower = text.toLowerCase();
  return REMOVAL_KEYWORDS.some( ( kw ) => lower.includes( kw ) );
};

export const useAiConversation = ( options: UseAiConversationOptions ): UseAiConversationResult => {
  const {
    apiUrl,
    previewHtml,
    originalPreviewHtml,
    publishTitle,
    selectedItem,
    selectedBlockIndex,
    selectedBlockHtml,
    iframeRef,
    setPreviewHtml,
    setPublishTitle,
    setMetaTitle,
    setMetaExcerpt,
    setMetaFeaturedImageUrl,
    clearSelection,
  } = options;

  const [ messages, setMessages ] = useState<Message[]>( [] );
  const [ input, setInput ] = useState( '' );
  const [ isLoading, setIsLoading ] = useState( false );
  const [ historyEntries, setHistoryEntries ] = useState<HistoryEntry[]>( [] );
  const [ isHistoryOpen, setIsHistoryOpen ] = useState( false );
  const [ hasAIGenerated, setHasAIGenerated ] = useState( false );
  const [ conversationId, setConversationId ] = useState<string | null>( null );
  const [ responseId, setResponseId ] = useState<string | null>( null );
  
  // Track the last HTML generated by the AI so follow-up requests can 
  // target it directly without needing the full page context or losing track of the edit.
  const [ lastGeneratedHtml, setLastGeneratedHtml ] = useState<string | null>( null );
  
  const chatMessagesRef = useRef<HTMLDivElement>( null );
  const streamEnabled = ( window as any )?.nfdAIPageDesigner?.enableStreaming !== false;

  useEffect( () => {
    // If the user manually selects a new block, clear the follow-up edit tracking
    // so we don't accidentally apply a string replacement in the wrong place later.
    if ( selectedBlockIndex !== null ) {
      setLastGeneratedHtml( null );
    }
  }, [ selectedBlockIndex ] );

  useEffect( () => {
    if ( ! chatMessagesRef.current ) {
      return;
    }
    chatMessagesRef.current.scrollTop = chatMessagesRef.current.scrollHeight;
  }, [ messages, isLoading ] );

  const appendAssistantMessage = useCallback( ( message: Message ) => {
    setMessages( ( prev ) => [ ...prev, message ] );
  }, [] );

  const handleSend = useCallback( async ( overrideText?: string ) => {
    const text = ( overrideText !== undefined ? overrideText : input ).trim();
    const wantsExcerpt = /excerpt/i.test( text );
    const wantsFeaturedImage = /(featured image|feature image|featured-image|featured-img)/i.test( text );
    const wantsTitle = /(title|headline|page title|post title|rename)/i.test( text );
    if ( ! text || isLoading ) {
      return;
    }

    setInput( '' );
    const userMsg: Message = { role: 'user', content: text };
    const newMessages = [ ...messages, userMsg ];
    setMessages( newMessages );

    const applyMetadataOnlyResponse = ( responseData: any ) => {
      const title = responseData?.title || '';
      const excerpt = responseData?.excerpt || '';
      const summary = responseData?.summary || '';

      const applied: string[] = [];
      if ( title && ( ! selectedItem || wantsTitle ) ) {
        setPublishTitle( title );
        setMetaTitle( title );
        applied.push( 'title' );
      }
      if ( excerpt ) {
        setMetaExcerpt( excerpt );
        applied.push( 'excerpt' );
      }

      const fallback = applied.length
        ? `Updated ${ applied.join( ' and ' ) }.`
        : 'No changes were made.';

      setMessages( [
        ...newMessages,
        {
          role: 'assistant',
          content: summary || fallback,
          summary: summary || undefined,
        },
      ] );

      if ( responseData?.response_id ) {
        setResponseId( responseData.response_id );
      }
      if ( ! selectedItem && responseData?.conversation_id ) {
        setConversationId( responseData.conversation_id );
      }
    };

    const applyFinalResponse = ( rawContent: string, responseData: any, isFollowUpEdit: boolean ) => {
      const responseSummary = responseData?.summary ?? '';
      const title = responseData?.title || '';
      const fallbackSummary = selectedItem ? 'Update ready.' : 'New page ready.';

      setMessages( [
        ...newMessages,
        {
          role: 'assistant',
          content: responseSummary || fallbackSummary,
          summary: responseSummary || undefined,
          code: rawContent || undefined,
        },
      ] );

      if ( ! selectedItem && responseData?.conversation_id ) {
        setConversationId( responseData.conversation_id );
      }

      if ( responseData?.response_id ) {
        setResponseId( responseData.response_id );
      }

      let finalHtml = rawContent.trim();
      finalHtml = finalHtml.replace( /<!--(?![\s\S]*?-->)[\s\S]*$/u, '' );

      const stack: string[] = [];
      const regex = /<!--\s*(\/?)wp:([\w\/-]+)(?:\s[^-]*)?\s*(\/?)-->/gi;
      let match;

      while ( ( match = regex.exec( finalHtml ) ) !== null ) {
        const isClosing = match[1].trim() === '/';
        const blockName = match[2].trim();
        const isSelfClosing = match[3].trim() === '/';

        if ( isSelfClosing ) {
          continue;
        }

        if ( isClosing ) {
          if ( stack.length > 0 && stack[ stack.length - 1 ] === blockName ) {
            stack.pop();
          }
        } else {
          stack.push( blockName );
        }
      }

      while ( stack.length > 0 ) {
        const blockName = stack.pop();
        finalHtml += `\n<!-- /wp:${ blockName } -->`;
      }

      const html = extractHtml( finalHtml );
      if ( html ) {
        const timestamp = new Date().toLocaleTimeString( [], { hour: '2-digit', minute: '2-digit' } );
        const historyLabelPrefix = selectedBlockIndex !== null ? 'Targeted edit' : 'Edit';
        const historyLabelDetail = text.length ? `: ${ text.substring( 0, 60 ) }` : '';
        const historyLabel = `${ historyLabelPrefix }${ historyLabelDetail }`;
        const historyId = `${ Date.now() }-${ Math.random().toString( 16 ).slice( 2 ) }`;
        const addHistoryEntry = ( htmlSnapshot: string ) => {
          if ( htmlSnapshot && htmlSnapshot !== previewHtml ) {
            setHistoryEntries( ( prev ) => [
              ...prev,
              {
                id: historyId,
                html: htmlSnapshot,
                label: historyLabel,
                timestamp,
                publishTitle: title || publishTitle,
              },
            ] );
          }
        };

        if ( selectedBlockIndex !== null && selectedBlockHtml !== null ) {
          if ( /<!--\s*wp:/.test( html ) ) {
            // AI returned full Gutenberg block markup — apply as full-page update.
            setPreviewHtml( html );
            addHistoryEntry( html );
            setLastGeneratedHtml( null );
            clearSelection( iframeRef );
          } else {
            // AI returned a raw HTML fragment — patch just the selected block in the DOM.
            const doc = iframeRef.current?.contentDocument;
            if ( doc ) {
              const wrapper = doc.querySelector( `.nfd-block-wrapper[data-block-index="${ selectedBlockIndex }"]` );
              if ( wrapper ) {
                wrapper.innerHTML = html;

                const root = doc.getElementById( 'nfd-preview-root' );
                let newHtml = '';

                if ( root ) {
                  const clone = root.cloneNode( true ) as HTMLElement;

                  clone.querySelectorAll( '.nfd-block-wrapper' ).forEach( ( w ) => {
                    while ( w.firstChild ) {
                      w.parentNode?.insertBefore( w.firstChild, w );
                    }
                    w.parentNode?.removeChild( w );
                  } );

                  clone.querySelectorAll( 'span' ).forEach( ( s ) => {
                    if ( s.attributes.length === 0 ) {
                      while ( s.firstChild ) {
                        s.parentNode?.insertBefore( s.firstChild, s );
                      }
                      s.parentNode?.removeChild( s );
                    }
                  } );

                  newHtml = clone.innerHTML;
                } else {
                  newHtml = Array.from( doc.querySelectorAll( '.nfd-block-wrapper' ) )
                    .map( ( w ) => w.innerHTML )
                    .join( '\n\n' );
                }

                setPreviewHtml( newHtml );
                addHistoryEntry( newHtml );
                setLastGeneratedHtml( html );
                clearSelection( iframeRef );
              }
            } else {
              setPreviewHtml( previewHtml );
              clearSelection( iframeRef );
            }
          }
        } else if ( isFollowUpEdit && lastGeneratedHtml && previewHtml ) {
          // The user made a follow-up request to a targeted edit without re-selecting.
          // Replace the previously generated block(s) with the newly generated block(s).
          const newHtml = previewHtml.replace( lastGeneratedHtml, html );
          setPreviewHtml( newHtml );
          addHistoryEntry( newHtml );
          setLastGeneratedHtml( html );
        } else {
          setPreviewHtml( html );
          addHistoryEntry( html );
          setLastGeneratedHtml( null );
        }
        const isFirstGeneration = ! selectedItem && ! hasAIGenerated;
        setHasAIGenerated( true );
        if ( title && ( isFirstGeneration || wantsTitle ) ) {
          setPublishTitle( title );
          setMetaTitle( title );
        }
        if ( wantsExcerpt ) {
          const excerpt = responseData?.excerpt || '';
          if ( excerpt ) {
            setMetaExcerpt( excerpt );
          }
        }
        if ( wantsFeaturedImage ) {
          const featuredImageUrl = responseData?.featured_image_url || null;
          if ( featuredImageUrl ) {
            setMetaFeaturedImageUrl( featuredImageUrl );
          }
        }
      }
    };

    try {
      setIsLoading( true );

      // Shared helper: remove the selected block from the live iframe DOM and sync state.
      const removeSelectedBlock = () => {
        const doc = iframeRef.current?.contentDocument;
        if ( ! doc ) {
          return;
        }
        const wrapper = doc.querySelector( `.nfd-block-wrapper[data-block-index="${ selectedBlockIndex }"]` );
        if ( ! wrapper ) {
          return;
        }
        wrapper.remove();

        const root = doc.getElementById( 'nfd-preview-root' );
        let newHtml = '';

        if ( root ) {
          const clone = root.cloneNode( true ) as HTMLElement;

          clone.querySelectorAll( '.nfd-block-wrapper' ).forEach( ( w ) => {
            while ( w.firstChild ) {
              w.parentNode?.insertBefore( w.firstChild, w );
            }
            w.parentNode?.removeChild( w );
          } );

          clone.querySelectorAll( 'span' ).forEach( ( s ) => {
            if ( s.attributes.length === 0 ) {
              while ( s.firstChild ) {
                s.parentNode?.insertBefore( s.firstChild, s );
              }
              s.parentNode?.removeChild( s );
            }
          } );

          newHtml = clone.innerHTML;
        } else {
          newHtml = Array.from( doc.querySelectorAll( '.nfd-block-wrapper' ) )
            .map( ( w ) => w.innerHTML )
            .join( '\n\n' );
        }

        if ( newHtml ) {
          const timestamp = new Date().toLocaleTimeString( [], { hour: '2-digit', minute: '2-digit' } );
          const historyId = `${ Date.now() }-${ Math.random().toString( 16 ).slice( 2 ) }`;
          if ( newHtml !== previewHtml ) {
            setHistoryEntries( ( prev ) => [ ...prev, {
              id: historyId,
              html: newHtml,
              label: `Removed: ${ text.substring( 0, 60 ) }`,
              timestamp,
              publishTitle,
            } ] );
          }
          setPreviewHtml( newHtml );
          setHasAIGenerated( true );
        }
      };

      // Fast path: remove selected block without an AI round-trip.
      if ( selectedBlockIndex !== null && selectedBlockHtml !== null && isRemovalIntent( text ) ) {
        removeSelectedBlock();
        setMessages( [ ...newMessages, { role: 'assistant', content: 'Section removed.' } ] );
        clearSelection( iframeRef );
        return;
      }

      // Check if this is a metadata-only request first, before follow-up edit detection.
      // Metadata requests (excerpt, title, summary) should never send page content as context.
      const isMetadataRequest = /\b(add|create|generate|write)\s+(an?\s+)?(excerpt|title|summary)\b|^(excerpt|title|summary)$/i.test(text);
      
      // Detect if this is a follow-up request to a previously generated block.
      // This allows the AI to continue editing the block(s) it just made without needing
      // the user to manually re-select them, saving tokens and preserving page context.
      const isFollowUpEdit = !isMetadataRequest && selectedBlockIndex === null && lastGeneratedHtml !== null && !!previewHtml?.includes(lastGeneratedHtml);
      // When a block is selected, send the full page as context so the AI can return the complete
      // modified page. The clicked block's HTML goes in selected_block_markup to annotate the target.
      const contextMarkup = selectedBlockIndex !== null
        ? ( previewHtml || '' )
        : ( isFollowUpEdit ? lastGeneratedHtml : ( isMetadataRequest ? '' : previewHtml ) ) || '';

      const context: import('../api').GenerateContentContext = {
        current_markup: contextMarkup,
        post_id: selectedItem?.id,
        conversation_id: selectedItem ? undefined : conversationId || undefined,
        content_type: ( selectedItem?.type ?? 'page' ) as 'page' | 'post',
        ...( selectedBlockIndex !== null && selectedBlockHtml !== null ? { selected_block_markup: selectedBlockHtml } : {} ),
      };

      const shouldStream =
        streamEnabled &&
        ! selectedItem &&
        ! hasAIGenerated;

      if ( shouldStream ) {
        let streamBuffer = '';
        let finalData: any = null;
        let streamError: string | null = null;

        await generateContentStream( apiUrl, newMessages, context, ( event ) => {
          if ( event.type === 'delta' ) {
            streamBuffer += event.text;
            
            // If it's a follow up edit, we need to show the stream in context
            if ( isFollowUpEdit && lastGeneratedHtml && previewHtml ) {
              setPreviewHtml( previewHtml.replace( lastGeneratedHtml, streamBuffer ) );
            } else if ( selectedBlockIndex === null ) {
              setPreviewHtml( streamBuffer );
            }
          }
          if ( event.type === 'snapshot' ) {
            streamBuffer = event.text;
            if ( isFollowUpEdit && lastGeneratedHtml && previewHtml ) {
              setPreviewHtml( previewHtml.replace( lastGeneratedHtml, streamBuffer ) );
            } else if ( selectedBlockIndex === null ) {
              setPreviewHtml( streamBuffer );
            }
          }
          if ( event.type === 'result' ) {
            finalData = event.data;
            if ( finalData?.content ) {
              if ( isFollowUpEdit && lastGeneratedHtml && previewHtml ) {
                setPreviewHtml( previewHtml.replace( lastGeneratedHtml, finalData.content ) );
              } else if ( selectedBlockIndex === null ) {
                setPreviewHtml( finalData.content );
              }
            }
          }
          if ( event.type === 'error' ) {
            streamError = event.message;
          }
        } );

        if ( streamError ) {
          setMessages( [ ...newMessages, { role: 'assistant', content: streamError } ] );
          return;
        }

        if ( ! finalData ) {
          setMessages( [ ...newMessages, { role: 'assistant', content: 'No response was generated. Please try again.' } ] );
          return;
        }

        if ( finalData.is_metadata_only || ( ! finalData.content && ( finalData.excerpt || finalData.title || finalData.summary ) ) ) {
          // Restore the original preview HTML which might have been temporarily 
          // overwritten by the AI streaming metadata comments to the UI.
          if ( previewHtml !== null ) {
            setPreviewHtml( previewHtml );
          }
          applyMetadataOnlyResponse( finalData );
          return;
        }

        applyFinalResponse( finalData.content || streamBuffer, finalData, isFollowUpEdit );
        return;
      }

      const response = await generateContent( apiUrl, newMessages, context );

      const rawContent = response?.data?.content ?? '';
      const serverMessage = response?.data?.message ?? '';

      // Message-only response: fast path signalled an error (e.g. Unsplash unavailable).
      // Show the message in chat without touching the preview.
      if ( ! rawContent && serverMessage ) {
        setMessages( [ ...newMessages, { role: 'assistant', content: serverMessage } ] );
        return;
      }

      if ( ! rawContent ) {
        // AI returned nothing for a removal-intent prompt — treat it as intentional removal.
        if ( selectedBlockIndex !== null && selectedBlockHtml !== null && hasRemovalKeyword( text ) ) {
          removeSelectedBlock();
          setMessages( [ ...newMessages, { role: 'assistant', content: 'Section removed.' } ] );
          clearSelection( iframeRef );
          return;
        }

        const data = response?.data;
        if ( data && ( data.is_metadata_only || data.excerpt || data.title || data.summary ) ) {
          applyMetadataOnlyResponse( data );
          return;
        }

        setMessages( [ ...newMessages, { role: 'assistant', content: 'No response was generated. Please try again.' } ] );
        return;
      }

      applyFinalResponse( rawContent, response?.data, isFollowUpEdit );
    } catch ( error: any ) {
      console.error( 'AI generation error:', error );
      setMessages( [
        ...newMessages,
        {
          role: 'assistant',
          content: `Error: ${ error.message || 'Failed to generate content' }`,
        },
      ] );
    } finally {
      setIsLoading( false );
    }
  }, [
    apiUrl,
    clearSelection,
    iframeRef,
    input,
    isLoading,
    messages,
    originalPreviewHtml,
    previewHtml,
    publishTitle,
    selectedBlockHtml,
    selectedBlockIndex,
    setHasAIGenerated,
    setInput,
    setMessages,
    setMetaExcerpt,
    setMetaFeaturedImageUrl,
    setMetaTitle,
    setPreviewHtml,
    setPublishTitle,
  ] );

  const handleConfirmRevertChanges = useCallback( () => {
    setPreviewHtml( originalPreviewHtml );
    setHasAIGenerated( false );
    setPublishTitle( '' );
    setHistoryEntries( [] );
    setIsHistoryOpen( false );
    setMessages( [] );
    setInput( '' );
    clearSelection( iframeRef );
  }, [ clearSelection, iframeRef, originalPreviewHtml, setHasAIGenerated, setMessages, setPreviewHtml, setPublishTitle ] );

  const handleRevertToEntry = useCallback( ( id: string ) => {
    const index = historyEntries.findIndex( ( entry ) => entry.id === id );
    if ( index === -1 ) {
      return;
    }
    const remainingHistory = historyEntries.slice( 0, index + 1 );
    const targetEntry = historyEntries[ index ];

    setHistoryEntries( remainingHistory );
    setPreviewHtml( targetEntry.html );
    setPublishTitle( targetEntry.publishTitle ?? '' );
    setHasAIGenerated( true );
    clearSelection( iframeRef );
  }, [
    clearSelection,
    historyEntries,
    iframeRef,
    setHasAIGenerated,
    setPreviewHtml,
    setPublishTitle,
  ] );

  const resetAiConversation = useCallback( () => {
    setMessages( [] );
    setInput( '' );
    setHistoryEntries( [] );
    setIsHistoryOpen( false );
    setHasAIGenerated( false );
    setConversationId( null );
    setResponseId( null );
    clearSelection( iframeRef );
  }, [ clearSelection, iframeRef ] );

  return {
    messages,
    input,
    isLoading,
    historyEntries,
    isHistoryOpen,
    hasAIGenerated,
    publishTitle,
    chatMessagesRef,
    setInput,
    setIsHistoryOpen,
    setPublishTitle,
    handleSend,
    handleConfirmRevertChanges,
    handleRevertToEntry,
    resetAiConversation,
    appendAssistantMessage,
  };
};

export default useAiConversation;
