<?php
/**
 * AI client for AI Page Designer.
 *
 * @package NewfoldLabs\WP\Module\AIPageDesigner\Services
 */

namespace NewfoldLabs\WP\Module\AIPageDesigner\Services;

use NewfoldLabs\WP\Module\Data\HiiveConnection;

/**
 * Encapsulates the JWT exchange and AI generation request/response handling.
 */
class AiClient {

	/**
	 * Request generated content from the AI service.
	 *
	 * @param array $ai_messages Message payload for the AI service.
	 * @param array $options Optional settings (previous_response_id).
	 * @return array|\WP_Error
	 */
	public function generate_content( array $ai_messages, array $options = array() ) {
		$hiive_token = HiiveConnection::get_auth_token();

		if ( ! $hiive_token ) {
			return new \WP_Error(
				'rest_forbidden',
				__( 'You are not authorized to make this call. Hiive authentication failed.', 'wp-module-ai-page-designer' ),
				array( 'status' => 403 )
			);
		}

		$jwt_token = $this->get_jwt_token( $hiive_token );
		if ( is_wp_error( $jwt_token ) ) {
			return $jwt_token;
		}

		$input_payload = array(
			'input' => $ai_messages,
			'model' => 'gpt-5.4-mini',
			'store' => true,
		);

		if ( ! empty( $options['previous_response_id'] ) && is_string( $options['previous_response_id'] ) ) {
			$input_payload['previous_response_id'] = $options['previous_response_id'];
		}

		$request_body = wp_json_encode(
			array(
				'promptId'      => '4d5d7866-cbaf-4274-ad72-f789e358965d',
				'inputPayload'  => $input_payload,
			)
		);

		$timeout_filter = static function () {
			return 120;
		};

		add_filter( 'http_request_timeout', $timeout_filter, 999 );

		try {
			$response = wp_remote_post(
				'https://api-gw.builderservices.io/ai-api/v1/response',
				array(
					'headers' => array(
						'Content-Type'  => 'application/json',
						'Authorization' => 'Bearer ' . $jwt_token,
					),
					'timeout' => 120,
					'body'    => $request_body,
				)
			);
		} finally {
			remove_filter( 'http_request_timeout', $timeout_filter, 999 );
		}

		if ( is_wp_error( $response ) ) {
			return new \WP_Error(
				'ai_service_timeout',
				sprintf(
					__( 'AI service request failed: %s', 'wp-module-ai-page-designer' ),
					$response->get_error_message()
				),
				array( 'status' => 408 )
			);
		}

		$response_code = wp_remote_retrieve_response_code( $response );
		$raw_body      = wp_remote_retrieve_body( $response );

		if ( 200 !== $response_code ) {
			$error_body = json_decode( $raw_body, true );

			if ( 400 === $response_code && isset( $error_body['payload']['reason'] ) ) {
				return new \WP_Error(
					'ai_generation_error',
					$error_body['payload']['reason'],
					array( 'status' => 400 )
				);
			}

			if ( isset( $error_body['payload'] ) ) {
				$payload_message = is_string( $error_body['payload'] ) ? $error_body['payload'] : wp_json_encode( $error_body['payload'] );
				return new \WP_Error(
					'ai_generation_error',
					$payload_message,
					array( 'status' => $response_code )
				);
			}

			$default_message = 'We are unable to process the request at this moment';
			if ( isset( $error_body['message'] ) ) {
				$default_message = $error_body['message'];
			} elseif ( isset( $error_body['error'] ) && is_array( $error_body['error'] ) && isset( $error_body['error']['message'] ) ) {
				$default_message = $error_body['error']['message'];
			}

			return new \WP_Error(
				'ai_generation_error',
				$default_message,
				array( 'status' => $response_code )
			);
		}

		$result      = json_decode( wp_remote_retrieve_body( $response ), true );
		$content     = $this->extract_content_from_response( $result );
		$response_id = $this->extract_response_id( $result );

		if ( empty( $content ) ) {
			return new \WP_Error(
				'ai_generation_error',
				__( 'No content generated by AI service', 'wp-module-ai-page-designer' ),
				array( 'status' => 500 )
			);
		}

		return array(
			'content'     => $content,
			'response_id' => $response_id,
		);
	}

	/**
	 * Exchange Hiive token for JWT token from JWT worker.
	 *
	 * @param string $hiive_token The Hiive authentication token.
	 * @return string|\WP_Error
	 */
	private function get_jwt_token( $hiive_token ) {
		// Get brand from plugin or fallback to option.
		$brand = get_option( 'mm_brand', 'web' );
		$brand = apply_filters( 'newfold_ai_sitegen_brand', $brand );

		$headers = array(
			'Content-Type' => 'application/json',
			'Accept'       => 'application/json',
		);

		if ( $brand ) {
			$headers['X-Newfold-Brand'] = $brand;
		}

		$response = wp_remote_post(
			'https://cf-worker-newfold-services-jwt.bluehost.workers.dev/',
			array(
				'headers' => $headers,
				'timeout' => 30,
				'body'    => wp_json_encode(
					array(
						'hiiveToken' => $hiive_token,
					)
				),
			)
		);

		$response_code = wp_remote_retrieve_response_code( $response );

		if ( 200 !== $response_code ) {
			return new \WP_Error(
				'jwt_generation_error',
				__( 'Failed to obtain JWT token from JWT worker', 'wp-module-ai-page-designer' ),
				array( 'status' => $response_code )
			);
		}

		$result = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( ! isset( $result['jwt'] ) ) {
			return new \WP_Error(
				'jwt_generation_error',
				__( 'Invalid response from JWT worker', 'wp-module-ai-page-designer' ),
				array( 'status' => 500 )
			);
		}

		return $result['jwt'];
	}

	/**
	 * Extract the generated content from the AI response payload.
	 *
	 * @param array $result Decoded response body.
	 * @return string
	 */
	private function extract_content_from_response( array $result ) {
		$content = '';

		if ( isset( $result['outputPayload']['output'] ) && is_array( $result['outputPayload']['output'] ) ) {
			foreach ( $result['outputPayload']['output'] as $output_item ) {
				if ( isset( $output_item['type'] ) && 'message' === $output_item['type'] ) {
					if ( isset( $output_item['content'] ) && is_array( $output_item['content'] ) ) {
						foreach ( $output_item['content'] as $content_item ) {
							if ( isset( $content_item['type'] ) && 'output_text' === $content_item['type'] ) {
								if ( isset( $content_item['text'] ) ) {
									$content .= $content_item['text'];
								}
							}
						}
					}
				}
			}
		}

		// Fallback: try old OpenAiResponse structure for backward compatibility.
		if ( empty( $content ) && isset( $result['OpenAiResponse']['choices'] ) && is_array( $result['OpenAiResponse']['choices'] ) ) {
			foreach ( $result['OpenAiResponse']['choices'] as $choice ) {
				if ( isset( $choice['message']['content'] ) ) {
					$content .= $choice['message']['content'];
				}
			}
		}

		return $content;
	}

	/**
	 * Extract the response_id for conversation chaining.
	 *
	 * @param array $result Decoded response body.
	 * @return string|null
	 */
	private function extract_response_id( array $result ) {
		if ( isset( $result['responseMetadata']['response_id'] ) && is_string( $result['responseMetadata']['response_id'] ) ) {
			return $result['responseMetadata']['response_id'];
		}

		if ( isset( $result['outputPayload']['id'] ) && is_string( $result['outputPayload']['id'] ) ) {
			return $result['outputPayload']['id'];
		}

		return null;
	}
}
