<?php
/**
 * AI client for AI Page Designer.
 *
 * @package NewfoldLabs\WP\Module\AIPageDesigner\Services
 */

namespace NewfoldLabs\WP\Module\AIPageDesigner\Services;

use NewfoldLabs\WP\Module\Data\HiiveConnection;

/**
 * Encapsulates the JWT exchange and AI generation request/response handling.
 */
class AiClient {

	/**
	 * Request generated content from the AI service.
	 *
	 * @param array $ai_messages Message payload for the AI service.
	 * @param array $options Optional settings (previous_response_id).
	 * @return array|\WP_Error
	 */
	public function generate_content( array $ai_messages, array $options = array() ) {
		$hiive_token = HiiveConnection::get_auth_token();

		if ( ! $hiive_token ) {
			return new \WP_Error(
				'rest_forbidden',
				__( 'You are not authorized to make this call. Hiive authentication failed.', 'wp-module-ai-page-designer' ),
				array( 'status' => 403 )
			);
		}

		$jwt_token = $this->get_jwt_token( $hiive_token );
		if ( is_wp_error( $jwt_token ) ) {
			return $jwt_token;
		}

		$input_payload = array(
			'input'             => $ai_messages,
			'model'             => 'gpt-5.4-mini',
			'store'             => true,
			'max_output_tokens' => 5000,
		);

		if ( ! empty( $options['previous_response_id'] ) && is_string( $options['previous_response_id'] ) ) {
			$input_payload['previous_response_id'] = $options['previous_response_id'];
		}

		$request_body = wp_json_encode(
			array(
				'promptId'     => '4d5d7866-cbaf-4274-ad72-f789e358965d',
				'inputPayload' => $input_payload,
			)
		);

		$timeout_filter = static function () {
			return 120;
		};

		add_filter( 'http_request_timeout', $timeout_filter, 999 );

		try {
			$response = wp_remote_post(
				'https://api-gw.builderservices.io/ai-api/v1/response',
				array(
					'headers' => array(
						'Content-Type'  => 'application/json',
						'Authorization' => 'Bearer ' . $jwt_token,
					),
					'timeout' => 120,
					'body'    => $request_body,
				)
			);
		} finally {
			remove_filter( 'http_request_timeout', $timeout_filter, 999 );
		}

		if ( is_wp_error( $response ) ) {
			return new \WP_Error(
				'ai_service_timeout',
				sprintf(
					// translators: %s is the error message from the AI service.
					__( 'AI service request failed: %s', 'wp-module-ai-page-designer' ),
					$response->get_error_message()
				),
				array( 'status' => 408 )
			);
		}

		$response_code = wp_remote_retrieve_response_code( $response );
		$raw_body      = wp_remote_retrieve_body( $response );

		if ( 200 !== $response_code ) {
			$error_body = json_decode( $raw_body, true );

			if ( 400 === $response_code && isset( $error_body['payload']['reason'] ) ) {
				return new \WP_Error(
					'ai_generation_error',
					$error_body['payload']['reason'],
					array( 'status' => 400 )
				);
			}

			if ( isset( $error_body['payload'] ) ) {
				$payload_message = is_string( $error_body['payload'] ) ? $error_body['payload'] : wp_json_encode( $error_body['payload'] );
				return new \WP_Error(
					'ai_generation_error',
					$payload_message,
					array( 'status' => $response_code )
				);
			}

			$default_message = 'We are unable to process the request at this moment';
			if ( isset( $error_body['message'] ) ) {
				$default_message = $error_body['message'];
			} elseif ( isset( $error_body['error'] ) && is_array( $error_body['error'] ) && isset( $error_body['error']['message'] ) ) {
				$default_message = $error_body['error']['message'];
			}

			return new \WP_Error(
				'ai_generation_error',
				$default_message,
				array( 'status' => $response_code )
			);
		}

		$result      = json_decode( wp_remote_retrieve_body( $response ), true );
		$content     = $this->extract_content_from_response( $result );
		$response_id = $this->extract_response_id( $result );

		if ( empty( $content ) ) {
			return new \WP_Error(
				'ai_generation_error',
				__( 'No content generated by AI service', 'wp-module-ai-page-designer' ),
				array( 'status' => 500 )
			);
		}

		return array(
			'content'     => $content,
			'response_id' => $response_id,
		);
	}

	/**
	 * Stream generated content from the AI service.
	 *
	 * @param array    $ai_messages Message payload for the AI service.
	 * @param array    $options Optional settings (previous_response_id).
	 * @param callable $on_event Callback for stream events.
	 * @return string|\WP_Error Response ID or WP_Error on failure.
	 */
	public function stream_content( array $ai_messages, array $options, callable $on_event ) {
		$hiive_token = HiiveConnection::get_auth_token();

		if ( ! $hiive_token ) {
			return new \WP_Error(
				'rest_forbidden',
				__( 'You are not authorized to make this call. Hiive authentication failed.', 'wp-module-ai-page-designer' ),
				array( 'status' => 403 )
			);
		}

		$jwt_token = $this->get_jwt_token( $hiive_token );
		if ( is_wp_error( $jwt_token ) ) {
			return $jwt_token;
		}

		$request_body = wp_json_encode(
			array(
				'promptId'     => '4d5d7866-cbaf-4274-ad72-f789e358965d',
				'inputPayload' => $this->build_stream_input_payload( $ai_messages, $options ),
			)
		);

		$buffer      = '';
		$response_id = null;
		$curl_handle = curl_init( 'https://api-gw.builderservices.io/ai-api/v1/response/stream' );

		curl_setopt( $curl_handle, CURLOPT_POST, true );
		curl_setopt(
			$curl_handle,
			CURLOPT_HTTPHEADER,
			array(
				'Content-Type: application/json',
				'Authorization: Bearer ' . $jwt_token,
			)
		);
		curl_setopt( $curl_handle, CURLOPT_POSTFIELDS, $request_body );
		curl_setopt( $curl_handle, CURLOPT_TIMEOUT, 0 );
		curl_setopt(
			$curl_handle,
			CURLOPT_WRITEFUNCTION,
			function ( $ch, $chunk ) use ( &$buffer, &$response_id, $on_event ) {
				$buffer .= $chunk;

				while ( false !== ( $pos = strpos( $buffer, "\n\n" ) ) ) {
					$event_block = substr( $buffer, 0, $pos );
					$buffer      = substr( $buffer, $pos + 2 );

					$lines     = preg_split( "/\r?\n/", trim( $event_block ) );
					$event     = 'message';
					$data_lines = array();

					foreach ( $lines as $line ) {
						if ( 0 === strpos( $line, 'event:' ) ) {
							$event = trim( substr( $line, 6 ) );
							continue;
						}
						if ( 0 === strpos( $line, 'data:' ) ) {
							$data_lines[] = trim( substr( $line, 5 ) );
						}
					}

					if ( empty( $data_lines ) ) {
						continue;
					}

					$data = implode( "\n", $data_lines );
					if ( '[DONE]' === $data ) {
						$on_event( array( 'type' => 'done' ) );
						continue;
					}

					$payload = json_decode( $data, true );
					if ( is_array( $payload ) ) {
						$delta = $this->extract_stream_delta( $payload );
						if ( '' !== $delta ) {
							$on_event(
								array(
									'type' => 'delta',
									'text' => $delta
								)
							);
						} else {
							$snapshot = $this->extract_stream_snapshot( $payload );
							if ( '' !== $snapshot ) {
								$on_event(
									array(
										'type' => 'snapshot',
										'text' => $snapshot
									)
								);
							}
						}

						$maybe_response_id = $this->extract_response_id( $payload );
						if ( $maybe_response_id ) {
							$response_id = $maybe_response_id;
							$on_event(
								array(
									'type' => 'meta',
									'response_id' => $response_id
								)
							);
						}
					}
				}
				return strlen( $chunk );
			}
		);

		$ok = curl_exec( $curl_handle );
		if ( false === $ok ) {
			$error_message = curl_error( $curl_handle );
			curl_close( $curl_handle );
			return new \WP_Error(
				'ai_stream_error',
				// translators: %s is the error message from the AI service.
				sprintf( __( 'AI streaming request failed: %s', 'wp-module-ai-page-designer' ), $error_message ),
				array( 'status' => 500 )
			);
		}

		$response_code = curl_getinfo( $curl_handle, CURLINFO_RESPONSE_CODE );
		curl_close( $curl_handle );

		if ( $response_code && $response_code >= 400 ) {
			return new \WP_Error(
				'ai_stream_error',
				// translators: %s is the error code from the AI service.
				sprintf( __( 'AI streaming request failed: %s', 'wp-module-ai-page-designer' ), $response_code ),
				array( 'status' => $response_code )
			);
		}

		return $response_id;
	}

	/**
	 * Exchange Hiive token for JWT token from JWT worker.
	 *
	 * @param string $hiive_token The Hiive authentication token.
	 * @return string|\WP_Error
	 */
	private function get_jwt_token( $hiive_token ) {
		// Get brand from plugin or fallback to option.
		$brand = get_option( 'mm_brand', 'web' );
		$brand = apply_filters( 'newfold_ai_sitegen_brand', $brand );

		$headers = array(
			'Content-Type' => 'application/json',
			'Accept'       => 'application/json',
		);

		if ( $brand ) {
			$headers['X-Newfold-Brand'] = $brand;
		}

		$response = wp_remote_post(
			'https://cf-worker-newfold-services-jwt.bluehost.workers.dev/',
			array(
				'headers' => $headers,
				'timeout' => 30,
				'body'    => wp_json_encode(
					array(
						'hiiveToken' => $hiive_token,
					)
				),
			)
		);

		$response_code = wp_remote_retrieve_response_code( $response );

		if ( 200 !== $response_code ) {
			return new \WP_Error(
				'jwt_generation_error',
				__( 'Failed to obtain JWT token from JWT worker', 'wp-module-ai-page-designer' ),
				array( 'status' => $response_code )
			);
		}

		$result = json_decode( wp_remote_retrieve_body( $response ), true );

		if ( ! isset( $result['jwt'] ) ) {
			return new \WP_Error(
				'jwt_generation_error',
				__( 'Invalid response from JWT worker', 'wp-module-ai-page-designer' ),
				array( 'status' => 500 )
			);
		}

		return $result['jwt'];
	}

	/**
	 * Extract the generated content from the AI response payload.
	 *
	 * @param array $result Decoded response body.
	 * @return string
	 */
	private function extract_content_from_response( array $result ) {
		$content = '';

		if ( isset( $result['outputPayload']['output'] ) && is_array( $result['outputPayload']['output'] ) ) {
			foreach ( $result['outputPayload']['output'] as $output_item ) {
				if ( isset( $output_item['type'] ) && 'message' === $output_item['type'] ) {
					if ( isset( $output_item['content'] ) && is_array( $output_item['content'] ) ) {
						foreach ( $output_item['content'] as $content_item ) {
							if ( isset( $content_item['type'] ) && 'output_text' === $content_item['type'] ) {
								if ( isset( $content_item['text'] ) ) {
									$content .= $content_item['text'];
								}
							}
						}
					}
				}
			}
		}

		// Fallback: try old OpenAiResponse structure for backward compatibility.
		if ( empty( $content ) && isset( $result['OpenAiResponse']['choices'] ) && is_array( $result['OpenAiResponse']['choices'] ) ) {
			foreach ( $result['OpenAiResponse']['choices'] as $choice ) {
				if ( isset( $choice['message']['content'] ) ) {
					$content .= $choice['message']['content'];
				}
			}
		}

		return $content;
	}

	/**
	 * Extract the response_id for conversation chaining.
	 *
	 * @param array $result Decoded response body.
	 * @return string|null
	 */
	private function extract_response_id( array $result ) {
		if ( isset( $result['type'], $result['response_id'] ) && 'completed' === $result['type'] ) {
			return (string) $result['response_id'];
		}

		if ( isset( $result['type'], $result['response']['id'] ) ) {
			if ( 'response.created' === $result['type'] || 'response.done' === $result['type'] ) {
				return (string) $result['response']['id'];
			}
		}
		if ( isset( $result['type'], $result['response']['id'] ) ) {
			if ( 'response.created' === $result['type'] || 'response.done' === $result['type'] ) {
				return (string) $result['response']['id'];
			}
		}

		if ( isset( $result['responseMetadata']['response_id'] ) && is_string( $result['responseMetadata']['response_id'] ) ) {
			return $result['responseMetadata']['response_id'];
		}

		if ( isset( $result['outputPayload']['id'] ) && is_string( $result['outputPayload']['id'] ) ) {
			return $result['outputPayload']['id'];
		}

		return null;
	}

	/**
	 * Build the input payload for the AI service.
	 *
	 * @param array $ai_messages Message payload.
	 * @param array $options Optional settings.
	 * @return array
	 */
	private function build_input_payload( array $ai_messages, array $options ) {
		$input_payload = array(
			'input' => $ai_messages,
			'model' => 'gpt-5.4-mini',
			'store' => true,
		);

		if ( ! empty( $options['previous_response_id'] ) && is_string( $options['previous_response_id'] ) ) {
			$input_payload['previous_response_id'] = $options['previous_response_id'];
		}

		return $input_payload;
	}

	/**
	 * Build the input payload for the streaming AI service.
	 *
	 * @param array $ai_messages Message payload.
	 * @param array $options Optional settings.
	 * @return array
	 */
	private function build_stream_input_payload( array $ai_messages, array $options ) {
		$input_payload = array(
			'model' => 'gpt-5.4-mini',
			'input' => wp_json_encode( $ai_messages ),
			'store' => true,
			'max_output_tokens' => 5000,
		);

		if ( ! empty( $options['previous_response_id'] ) && is_string( $options['previous_response_id'] ) ) {
			$input_payload['previous_response_id'] = $options['previous_response_id'];
		}

		return $input_payload;
	}

	/**
	 * Extract streaming text deltas from a stream payload.
	 *
	 * @param array $payload Stream payload.
	 * @return string
	 */
	private function extract_stream_delta( array $payload ) {
		if ( isset( $payload['Delta'] ) && is_string( $payload['Delta'] ) ) {
			return $payload['Delta'];
		}

		if ( isset( $payload['type'] ) && 'response.output.text.delta' === $payload['type'] && isset( $payload['delta'] ) ) {
			return (string) $payload['delta'];
		}

		if ( isset( $payload['type'], $payload['delta'] ) && is_string( $payload['delta'] ) ) {
			if ( substr( $payload['type'], -6 ) === '.delta' ) {
				return $payload['delta'];
			}
		}

		if ( isset( $payload['delta'] ) && is_string( $payload['delta'] ) ) {
			return $payload['delta'];
		}

		if ( isset( $payload['delta']['content'] ) ) {
			return (string) $payload['delta']['content'];
		}

		if ( isset( $payload['choices'][0]['delta']['content'] ) ) {
			return (string) $payload['choices'][0]['delta']['content'];
		}

		if ( isset( $payload['outputPayload']['output'] ) && is_array( $payload['outputPayload']['output'] ) ) {
			$text = '';
			foreach ( $payload['outputPayload']['output'] as $output_item ) {
				if ( isset( $output_item['type'] ) && 'message' === $output_item['type'] && isset( $output_item['content'] ) ) {
					foreach ( (array) $output_item['content'] as $content_item ) {
						if ( isset( $content_item['type'] ) && 'output_text' === $content_item['type'] && isset( $content_item['text'] ) ) {
							$text .= $content_item['text'];
						}
					}
				}
			}
			return $text;
		}

		if ( isset( $payload['content'] ) ) {
			return (string) $payload['content'];
		}

		if ( isset( $payload['text'] ) ) {
			return (string) $payload['text'];
		}

		return '';
	}

	/**
	 * Extract snapshot text from a stream payload.
	 *
	 * @param array $payload Stream payload.
	 * @return string
	 */
	private function extract_stream_snapshot( array $payload ) {
		if ( isset( $payload['Text'] ) && is_string( $payload['Text'] ) ) {
			return $payload['Text'];
		}

		if ( isset( $payload['Part']['Text'] ) && is_string( $payload['Part']['Text'] ) ) {
			return $payload['Part']['Text'];
		}

		return '';
	}
}
